language: java
jdk:
  - oraclejdk15

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: amazin-online-bookstore-oa

services:
  - postgresql

before_script:
  - psql -c 'create database amazinbookstore;' -U postgres

env:
  - JDBC_TEST_DATABASE_URL=jdbc:postgresql://localhost:5432/amazinbookstore JDBC_TEST_DATABASE_USERNAME=postgres JDBC_TEST_DATABASE_PASSWORD=postgres